version: "3"

services:
    web:
        build: 
            context: .
            dockerfile: app/Dockerfile
        ports:
            - "3002:3000"
        links:
            - db
        volumes:
            - "./app:/app" #共有フォルダの設定
        stdin_open: true
    db:
        image: postgres:9.6.5
        expose:
            - "5432"
        environment:
            - TZ=Asia/Tokyo 
